export function HomePage() {
    return (
        <>
            <div className="d-flex flex-column h-full text-red-600">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi accusamus excepturi consequatur adipisci officia, laborum ratione corporis soluta rem tempore perferendis id quo veniam eligendi voluptas laudantium nihil illo dolor sapiente voluptates? Dolores itaque recusandae perferendis minima repellendus doloribus commodi, veritatis autem tempora, voluptate totam pariatur. Vero exercitationem sed pariatur?</p>
                <p>Cum amet, eaque modi laudantium soluta doloribus quia deserunt minima eos aut delectus, laboriosam sed possimus perspiciatis officiis eligendi laborum ut quod dolor natus consequatur! Aperiam tempore amet maiores nisi nam repudiandae aliquam, libero perspiciatis quisquam beatae debitis, placeat nostrum, illo eius eveniet voluptatem quis! Ipsum dignissimos pariatur facilis quia?</p>
                <p>Illo molestiae aliquam impedit ducimus. Hic voluptas ad iusto laboriosam obcaecati voluptate corrupti tempora ex accusantium! Sunt aliquam quas reprehenderit quibusdam porro? Voluptatem asperiores aliquam ratione unde ipsam nesciunt hic explicabo magni sapiente? Ab culpa autem iste sint porro necessitatibus molestiae quam. Qui eos quos incidunt dolorem quidem, quis sequi!</p>
                <p>Iure sit fuga eligendi distinctio reprehenderit reiciendis quis laboriosam ipsa porro quasi dignissimos aperiam maxime doloremque est animi tempora quam optio error sapiente, dolorem a nemo dolorum corrupti! Temporibus nobis ratione accusantium voluptates incidunt repellat enim optio consequuntur itaque vitae error veniam dolorem quos, perferendis provident blanditiis sit illo repudiandae.</p>
                <p>Beatae deserunt ratione sunt tenetur atque consequuntur, inventore adipisci est temporibus ipsam nihil tempore ut fugiat vero facilis facere sint veritatis ipsa ullam libero sapiente reprehenderit architecto. Nobis error quos sapiente architecto facilis quas placeat cupiditate at. Commodi eos possimus magnam quod, quam animi, accusantium nostrum quaerat quae eius quibusdam.</p>
                <p>Animi eligendi reiciendis recusandae cum incidunt laborum, illum nulla accusantium fuga id sapiente dignissimos laboriosam maiores cumque deserunt et facere qui, saepe aliquid, unde tempore quis. Voluptate doloremque saepe hic quas doloribus, consequatur eligendi harum laudantium molestias. Sit itaque culpa sapiente error in repellat labore commodi, odio, quo provident harum.</p>
                <p>Sunt quia quisquam, tempora numquam animi, culpa similique perspiciatis nulla officiis deserunt veritatis accusantium totam iusto minima recusandae ipsam saepe nesciunt voluptates itaque. Magni minima eos, fugit consequatur cum ipsam exercitationem reprehenderit, itaque, similique voluptas omnis assumenda alias fuga. Excepturi deleniti nulla sed voluptates deserunt numquam beatae tenetur. Eum, dolores?</p>
                <p>Iste nihil facere dolores mollitia repellat quo rem ratione numquam eligendi at provident quibusdam voluptatibus voluptate iure id, dolorum voluptates deleniti assumenda. Quibusdam consectetur quos in libero ullam consequuntur eum, optio dolor, porro recusandae tempore laboriosam nobis! Voluptatibus magni odio dignissimos ut esse omnis alias. Ipsum numquam reiciendis cumque ab?</p>
                <p>Impedit quidem doloribus mollitia velit error minus reprehenderit reiciendis commodi ab facere in, hic esse nihil laudantium excepturi magnam repellat omnis ut distinctio officiis animi. Deserunt dolor adipisci explicabo quos dignissimos atque, voluptatem maiores dolorum expedita ex, a id at numquam accusantium ipsum aut corporis optio est! Exercitationem, et omnis!</p>
                <p>Sunt, rem voluptatibus. Porro eum laboriosam ipsum, quam nihil vitae sit delectus quae dolor. Quibusdam accusantium eos illum similique repellat esse, possimus assumenda provident perspiciatis earum aut repellendus natus eaque, quis animi ipsum et obcaecati at maiores cumque temporibus! Necessitatibus veniam in voluptate possimus porro voluptas ullam maxime iste dolorum?</p>
            </div>
        </>
    )
}